version: '3'
services:
  # db:
  #   image: mysql:latest
  #   restart: always
  #   # volumes:
  #   #   - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   environment:
  #     MYSQL_ROOT_PASSWORD: admin
  #     MYSQL_USER: bruniapi
  #     MYSQL_PASSWORD: P@ssw0rd
  #     MYSQL_DATABASE: bruniapi
  #     MYSQL_ROOT_HOST: '%'
  #   ports:
  #     - "9999:3306"

  api:
    build: .
    ports:
      - "5000:80"
